// playgrounds/vue/src/components/demo.vue
<script setup lang="ts">
import { constValue } from '@common/const'

// import { useMounted } from '../hooks';
import { useMounted } from '@hooks'
import Log1 from './log1.vue'

const isMounted = useMounted()
</script>

<template>
  <div>
    <h2>demo.vue: constValue: {{ constValue }}</h2>
    <h2>demo.vue:isMounted: {{ isMounted }}</h2>
    <Log1 />
  </div>
</template>

// playgrounds/react/src/components/demo.tsx
// import { constValue } from '../common'
// import { constValue } from '@common/const'
import { constValue } from '@common'
// please use @hooks to import instead of【../hooks】
import { useIsMounted } from '../hooks';
// import { useIsMounted } from '@hooks';
import Log1 from './log1'


export default function Demo() {
const isMounted = useIsMounted()

  return (
    <div>
  <h2>demo.tsx: constValue: { constValue }</h2>
  <h2>demo.tsx:isMounted: { isMounted }</h2>
  <Log1 />
</div>
  )
}
