// playgrounds/react/src/app.tsx
import type { FC } from 'react'


import { constValue } from '@common/const'
import { useCommon } from '@common/utils'
import { useIsMounted } from './hooks';
import Demo from './components/demo'
import Log1 from './components/log1'




const index: FC = () => {

  const isMounted = useIsMounted()

useCommon()

  return (
    <div>
      <h1>app.tsx constValue: { constValue }</h1>
      <h2>app.tsx mounted: { isMounted }</h2>
      <br/> 
      <Demo /> 
      <Log1 /> 
    </div>
  )
}


export default index

// playgrounds/vue/src/App.vue
<script lang="ts" setup>
import { constValue } from '@common/const'
import { useCommon } from '@common/utils'
import { useMounted } from './hooks';
import Demo from './components/demo.vue'
import Log1 from './components/log1.vue'

const isMounted = useMounted()

useCommon()
</script>

<template>
  <h1>app.vue constValue: {{ constValue }}</h1>
  <h2>app.vue mounted: {{ isMounted }}</h2>
  <br/> 
  <demo /> 
  <log1 /> 
</template>
